[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  # DEEPSEEK_API_KEY should be configured in Netlify dashboard
  # Environment Variables section for security

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@deepseek-ai/deepseek-api"]
  
[[functions."diagnosis"]]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"